# Generated by Django 4.0.7 on 2022-08-10 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_remove_activity_photo_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='participants',
        ),
    ]
